# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend
#   namespace: roboshop
#   labels:
#     component: frontend
#     project: roboshop
#     tier: web
# data:
#     CART_ENDPOINT: "CART:8080"
#     DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata: # Deployment metadata
  name: frontend
  namespace: roboshop # Namespace for the deployment
  labels:
    component: frontend
    project: roboshop
    tier: web
    # This is the deployment for frontend
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      component: frontend
      project: roboshop
      tier: web
# this is pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: roboshop
        tier: web
    spec:
      containers:
        - name: frontend
          image: nagaraj411/frontend:v1 # Frontend image
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop # Namespace for the service
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  type: LoadBalancer # Service type
  # This service will be exposed to the outside world
  selector:
    component: frontend
    project: roboshop
    tier: web
  # This service will route traffic to the frontend pods
  ports:
  - protocol: TCP # Protocol for the service
    port: 80 # frontend default service port
    targetPort: 80 # container port