apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="
---
apiVersion: apps/v1
kind: Deployment
metadata: # Deployment metadata
  name: rabbitmq
  namespace: roboshop # Namespace for the deployment
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
    # This is the deployment for RabbitMQ
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database
# this is pod definition
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3 # RabbitMQ image
          envFrom:
          - secretRef:
              name: rabbitmq # Reference to the ConfigMap

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop # Namespace for the service
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
  - protocol: TCP # Protocol for the service
    port: 5672 # RabbitMQ default service port
    targetPort: 5672 # container port