apiVersion: apps/v1
kind: Deployment
metadata: # Deployment metadata
  name: mongodb
  namespace: roboshop # Namespace for the deployment
  labels:
    component: mongodb
    project: roboshop
    tier: database
    # This is the deployment for MongoDB
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database
# this is pod definition
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
        - name: mongodb
          image: nagaraj411/mongodb:v1 # MongoDB image
-----
          
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop # Namespace for the service
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP # Protocol for the service
    port: 27017 # MongoDB default port
    targetPort: 27017 # Port on the container to forward traffic to
