apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata: # Deployment metadata
  name: user
  namespace: roboshop # Namespace for the deployment
  labels:
    component: user
    project: roboshop
    tier: app
    # This is the deployment for user
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: app
# this is pod definition
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: app
    spec:
      containers:
        - name: user
          image: nagaraj411/user:v1 # User image
          envFrom:
          - configMapRef:
              name: user # Reference to the ConfigMap
---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop # Namespace for the service
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  selector:
    component: user
    project: roboshop
    tier: app
  ports:
  - protocol: TCP # Protocol for the service
    port: 8080 # user default service port
    targetPort: 8080 # container port