apiVersion: apps/v1
kind: Deployment
metadata: # Deployment metadata
  name: redis
  namespace: roboshop # Namespace for the deployment
  labels:
    component: redis
    project: roboshop
    tier: database
    # This is the deployment for Redis
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database
# this is pod definition
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database
    spec:
      containers:
        - name: redis
          image: redis:v1 # Redis image

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop # Namespace for the service
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP # Protocol for the service
    port: 6379 # Redis default service port
    targetPort: 6379 # container port